!*==I_DFDC.f90  processed by SPAG 7.25DB at 08:52 on  3 Feb 2020



MODULE I_DFDC
    IMPLICIT NONE
    !
    ! PARAMETER definitions
    !
    REAL, PARAMETER :: PI = 3.1415926535897932384, PI2I = 0.5 / PI, &
            & DTR = PI / 180.
    INTEGER, PARAMETER :: IBX = 1000, NEX = 30, NRPNX = 4, &
            & IPX = 2000, ICX = 2000, NQSPX = 5, &
            & NSEGX = 10, NMODX = 10, NPNTX = 200, &
            & NPOLX = 10, NCX = ICX - NEX, &
            & NSX = 2 * NEX, NSYSX = ICX + NEX, &
            & NUX = IPX + NEX + 2, NGLVX = 4 * NSEGX, &
            & NGLPX = NMODX, NRHSX = NGLVX + NGLPX + &
            & 1, IPAL = 1, IPCL = 2, IPCD = 3, &
            & IPCM = 4, IPCV = 5, IPMA = 7, &
            & IPQI = 10, IPTOT = 10, JPCX = 1, &
            & JPCY = 2, JPCM = 3, JPGAM = 4, &
            & JPSIG = 5, JPSOUR = 6, JPCIRC = 7, &
            & JPDBLX = 8, JPDBLY = 9, JPTOT = 9, &
            & KPTP = 1, KPTN = 2, KPTOT = 2, &
            & JCPLT = 1, JQPLT = 2, JAPLT = 3, &
            & NBLVX = 12, NDRGX = 10, IDX = 30, &
            & NRX = 3, IRX = 30, NAX = 20, &
            & NDX = 15, IX = 200, JX = 60, &
            & NAFX = 12, NPX = 200, NLSX = 36
    REAL, PARAMETER :: MTI = 39.370079, DTRX = PI / 180.
    INTEGER, PARAMETER :: NTCX = 10, IQXX = 360, IWX = 200
    !
    ! COMMON /CC_GEN/
    !
    CHARACTER(80) :: ANAME, ARGP1, ARGP2, CPFILE, FRFILE, &
            & ISPARS, NAME, PFILE
    CHARACTER(2), DIMENSION(99) :: PNUM
    CHARACTER(64) :: PREFIX
    !
    ! COMMON /CI_AERO/
    !
    INTEGER, DIMENSION(NRX) :: NAERO
    !
    ! COMMON /CI_BL/
    !
    INTEGER, DIMENSION(2, NEX) :: ICBLBEG, ICBLEND
    !
    ! COMMON /CI_CVP/
    !
    INTEGER, DIMENSION(NEX) :: ICFRST, ICLAST, ICSTG, IPFRST, &
            & IPLAST, IPTE1, IPTE2
    INTEGER, DIMENSION(ICX) :: ICTYPE, IPCO, IPCP
    INTEGER :: NCTOT, NPTOT
    !
    ! COMMON /CI_DRG/
    !
    INTEGER, DIMENSION(NDRGX) :: IELDRGOBJ, NDDEF
    INTEGER :: NDOBJ
    !
    ! COMMON /CI_FLO/
    !
    INTEGER, DIMENSION(IPX) :: IUGAM, IUSIG
    INTEGER :: IUQINF, NPSEQ, NU
    INTEGER, DIMENSION(NEX) :: IUVWK
    !
    ! COMMON /CI_GEN/
    !
    INTEGER, DIMENSION(NEX) :: IEWAKE
    INTEGER :: IMATYP, ITMAX, LUNDBG, NNAME, NPREFIX
    INTEGER, DIMENSION(IPX) :: IZERO
    !
    ! COMMON /CI_GEO/
    !
    INTEGER, DIMENSION(NEX) :: IBFRST, IBLAST, NBTYPE, NETYPE
    INTEGER :: IELGDES, NBEL, NBTOT, NEL, NMOD
    !
    ! COMMON /CI_GRD/
    !
    INTEGER, DIMENSION(ICX) :: IC2IG
    INTEGER, DIMENSION(NRX) :: IGROTOR
    INTEGER :: IGTECB, IGTEDW, II, JJ
    INTEGER, DIMENSION(IPX) :: IP2IG
    !
    ! COMMON /CI_PAN/
    !
    INTEGER, DIMENSION(NEX) :: NPAN
    INTEGER :: NPANDEF
    !
    ! COMMON /CI_PLT/
    !
    INTEGER, DIMENSION(NEX) :: ICOLEL, ISPLOT
    INTEGER :: IPTYPE
    !
    ! COMMON /CI_QSP/
    !
    INTEGER :: IELQDES, KQTARG, NQSP, NSEG
    INTEGER, DIMENSION(NSEGX) :: IELSEG, IPSEG1, IPSEG2
    INTEGER, DIMENSION(IPX) :: KSEGP
    !
    ! COMMON /CI_ROT/
    !
    INTEGER, DIMENSION(IRX, NRX) :: IAERO
    INTEGER, DIMENSION(NEX) :: IEL2IR
    INTEGER, DIMENSION(NRX) :: IELROTOR, IPROTCB, IPROTDW, &
            & IRTYPDEF, IRTYPE, NRBLD, NRDEF
    INTEGER, DIMENSION(IPX) :: IP2IR
    INTEGER, DIMENSION(IRX) :: IR2IEL
    INTEGER :: NRC, NROTOR, NRP, NRSTA, NRUPSTRM
    !
    ! COMMON /CI_SOLV/
    !
    INTEGER :: ITRMAXSOLV
    !
    ! COMMON /CI_SYS/
    !
    INTEGER, DIMENSION(ICX) :: IELDOFC, KSYSGMG, KSYSVNC
    INTEGER, DIMENSION(IPX) :: JAICGAM, JAICGTH, JAICSIG, &
            & JAICXYP, JSYSDXY, JSYSGAM, &
            & KSYSGAM
    INTEGER, DIMENSION(NEX) :: JAICVWK, JSYSQNC, KSYSGSS, &
            & KSYSKUT, KSYSQNC, KSYSQTT
    INTEGER, DIMENSION(NSYSX) :: JPSYS
    INTEGER, DIMENSION(4, 0:NSEGX) :: JSYSQSP, KSYSDNS
    INTEGER :: NAICGAM, NAICGTH, NAICSIG, NAICVWK, NAICXYP, &
            & NSYS
    !
    ! COMMON /CI_VELS/
    !
    INTEGER :: NINFL
    !
    ! COMMON /CI_WAK/
    !
    INTEGER :: NWAKE
    !
    ! COMMON /CL_BL/
    !
    LOGICAL :: LVISC
    !
    ! COMMON /CL_DRG/
    !
    LOGICAL :: LDRGOBJ
    !
    ! COMMON /CL_GEN/
    !
    LOGICAL :: LAGRID, LCOORD, LDBG, LDINT, LEPLT, LFREF, &
            & LGAMA, LGAMU, LGGRID, LGPARM, LGSYS, LGTICK, &
            & LLOAD, LNCVP, LNORM, LPACC, LPGRID, LPPLT, &
            & LPREF, LPSHO, LPSTAG, LQAIC, LQCNT, LQGIC, &
            & LQSYS, LRSPC, LRSPCDEF, LRSPCUSR, LSIGM, LSIGP, &
            & LSPLT, LSYSP, LVAIC, LVGIC, LVMAV, LVPLT, &
            & LWSHO, LXYMOV
    LOGICAL, DIMENSION(NEX) :: LBODY, LNDOF, LQNZR, LREVEL, &
            & LTPAN, LV1ZR, LV2ZR, LXBOD
    LOGICAL, DIMENSION(0:NUX) :: LUSET
    !
    ! COMMON /CL_QSP/
    !
    LOGICAL, DIMENSION(NSEGX) :: LDFIX1, LDFIX2, LNFIX1, LNFIX2
    LOGICAL :: LGNFIX, LGPLOT, LGSAME, LGSLOP, LGSPPL, LGSYMM, &
            & LHOMPL, LQCURV, LQQREV, LQREFL, LQSLOP, LQSPEC, &
            & LQSPPL, LQSREV, LQSVIS
    !
    ! COMMON /CL_ROT/
    !
    LOGICAL :: LBLDEF, LCHANGE
    LOGICAL, DIMENSION(IRX, NRX) :: LSTALLR
    !
    ! COMMON /CL_SOLV/
    !
    LOGICAL :: LCONV
    !
    ! COMMON /CL_WAK/
    !
    LOGICAL :: LWRLX
    !
    ! COMMON /CR_AERO/
    !
    REAL, DIMENSION(NDX, NAX, NRX) :: AERODATA
    REAL, DIMENSION(IRX, NRX) :: AZERO
    REAL, DIMENSION(NAX, NRX) :: XIAERO
    !
    ! COMMON /CR_BL/
    !
    REAL :: AMPMAX, UREN
    REAL, DIMENSION(NBLVX, ICX) :: BLDATA
    REAL, DIMENSION(0:NEX) :: CXVIS
    REAL, DIMENSION(2, NEX) :: SFIX, SSEP, STRN
    !
    ! COMMON /CR_CVP/
    !
    REAL, DIMENSION(2, ICX) :: ANC, CPL_QCL, CPR_QCR, DSC_DXY, &
            & QC, QCL, QCR, QC_XC, QC_YC
    REAL, DIMENSION(2, 2, ICX) :: ANC_DXY
    REAL, DIMENSION(2, IPX) :: ANP
    REAL, DIMENSION(2, 2, IPX) :: ANP_XYM, ANP_XYO, ANP_XYP
    REAL, DIMENSION(ICX) :: CPL, CPL_QINF, CPR, CPR_QINF, DSC, &
            & XC, YC
    REAL, DIMENSION(ICX, NUX) :: CPLU, CPRU
    REAL, DIMENSION(2, ICX, NUX) :: QCLU, QCRU
    REAL, DIMENSION(2, ICX, 0:NUX) :: QCU
    REAL, DIMENSION(2, IPX, ICX) :: QC_GAM, QC_GTH, QC_SIG, &
            & QC_XP, QC_YP
    REAL, DIMENSION(IPX) :: SP, VMAVG, XP, XPS, YP, YPS
    REAL, DIMENSION(NEX) :: SPLE, XPCENT, XPLE, XPMAXE, &
            & XPMINE, XPREFE, XPTE, XSTG, &
            & YPCENT, YPLE, YPMAXE, YPMINE, &
            & YPREFE, YPTE, YSTG
    REAL :: XPMAX, XPMIN, YPMAX, YPMIN
    !
    ! COMMON /CR_DRG/
    !
    REAL, DIMENSION(IDX, NDRGX) :: CDADEF, XDDEF, YDDEF
    !
    ! COMMON /CR_FLO/
    !
    REAL :: ALTH, DELTAT, GEE, MACH, MACH1, QINF, QINFP1, &
            & QINFP2, QINFPD, QREF, RHO, RMU, VSO
    REAL, DIMENSION(0:NEX) :: CD, CM, CX, CY
    REAL, DIMENSION(0:NEX, NUX) :: CDU, CMU, CXU, CYU
    REAL, DIMENSION(IPX) :: GAM, GAMVSP, GTH, SIG, SIGVSP
    REAL, DIMENSION(NEX) :: GAMP1, GAMP2, GAMPD, GAMSET, &
            & QNDOF, SIGP1, SIGP2, SIGPD, &
            & SIGSET, XTR1, XTR2
    REAL, DIMENSION(IPX, 0:NUX) :: GAMU, GTHU, SIGU
    REAL, DIMENSION(NEX, 0:NUX) :: QNDOFU
    !
    ! COMMON /CR_GEN/
    !
    REAL, DIMENSION(IBX) :: ONE, ZER
    CHARACTER(64) :: SVERSION
    REAL :: VERSION
    !
    ! COMMON /CR_GEO/
    !
    REAL, DIMENSION(NEX) :: AGBSUM, AREA2DA, AREA2DT, ASURFV, &
            & ASURFVT, DXBSUM, DYBSUM, EIXX2DA, &
            & EIXX2DT, EIXY2DA, EIXY2DT, EIYY2DA, &
            & EIYY2DT, RGYRXV, RGYRXVT, RGYRYV, &
            & RGYRYVT, SBLE, VOLUMV, VOLUMVT, &
            & XBCEN2DA, XBCEN2DT, XBCENV, &
            & XBCENVT, XBLE, XBMAXE, XBMINE, &
            & XBREFE, XBTE, XFBSUM, YBCEN2DA, &
            & YBCEN2DT, YBCENV, YBCENVT, YBLE, &
            & YBMAXE, YBMINE, YBREFE, YBTE, &
            & YFBSUM
    REAL :: DTEBOD, DTEPAN, XBMAX, XBMIN, YBMAX, YBMIN
    REAL, DIMENSION(IBX) :: SB, XB, XBS, YB, YBS
    REAL, DIMENSION(2) :: XGBOX, XWBOX, YGBOX, YWBOX
    !
    ! COMMON /CR_GRD/
    !
    REAL, DIMENSION(IX, JX) :: BGAMG, DHG, DSG, PG, POG, QG, &
            & QTG, QXG, QYG, RG, XG, YG
    REAL :: XGMIN
    REAL, DIMENSION(IX) :: XPOS
    REAL, DIMENSION(JX) :: YPOS
    !
    ! COMMON /CR_PAN/
    !
    REAL, DIMENSION(NRPNX, NEX) :: CRRAT, SRPN1, SRPN2
    REAL, DIMENSION(NEX) :: CVEX, FSLE, FSTE, SMOF
    REAL :: FPANDEF
    !
    ! COMMON /CR_PLT/
    !
    REAL :: CPLDEL, CPLFAC, CPLMAX, CPLMIN, CPXAR, CPYAR, &
            & FACA, GSF, PVFAC, QPLDEL, QPLFAC, QPLMAX, QPLMIN, &
            & QVFAC, XBOFF, XBSF, XOFA, XOFG, XPLDEL, XPLFAC, &
            & XPLMAX, XPLMIN, XPOFF, XPSF, XQOFF, XQSF, YBOFF, &
            & YBSF, YOFA, YOFG, YPLDEL, YPLFAC, YPLMAX, YPLMIN, &
            & YPOFF, YPSF, YQOFF, YQSF
    REAL, DIMENSION(0:7) :: SHF, SSIZEL
    REAL, DIMENSION(NEX) :: XELNUM, YELNUM
    !
    ! COMMON /CR_QSP/
    !
    REAL :: ALGAM, CLGAM, CMGAM, CXGAM, CYGAM, QIGAM, RLXMAX
    REAL, DIMENSION(NQSPX) :: ALQSP, CLQSP, CMQSP, CXQSP, &
            & CYQSP, QIQSP
    REAL, DIMENSION(4, IPX) :: FSPEC
    REAL, DIMENSION(IPX) :: GAMSP, QSGAM, SIGSP, SSPEC, XSPOC, &
            & XSPOCS, YSPOC, YSPOCS
    REAL, DIMENSION(NEX) :: QSPDEL, QSPMAX, QSPMIN, SSPDEL, &
            & SSPLE, SSPMAX, SSPMIN
    REAL, DIMENSION(4, NSEGX) :: QSPDOF
    REAL, DIMENSION(IPX, NQSPX) :: QSPEC, QSPECS
    !
    ! COMMON /CR_ROT/
    !
    REAL, DIMENSION(NRX) :: ADISK, ATIP, OMEGA, PINVR, PTOTR, &
            & PVISR, QINVR, QI_OMG, QI_QNF, &
            & QTOTR, QVISR, QV_DBE, QV_OMG, &
            & QV_QNF, RHUB, RTIP, TINVR, TI_OMG, &
            & TI_QNF, TTOTR, TVISR, TV_DBE, &
            & TV_OMG, TV_QNF, VAAVG, XDISK
    REAL, DIMENSION(IRX, NRX) :: ALFAR, BETADEF, BETAR, BETARP, &
            & BGAM, BGAMDEF, CDR, CHR, &
            & CHRDEF, CHRP, CLALF, CLR, CMR, &
            & DPII, DPSI, DPVI, DQII, DQVI, &
            & DTII, DTVI, MACHR, QI_GAM, &
            & QI_VA, QI_VT, QV_GAM, QV_VA, &
            & QV_VT, RER, TI_GAM, TI_VA, &
            & TI_VT, TV_GAM, TV_VA, TV_VT, &
            & XRC, XRP, YRC, YRDEF, YRP
    REAL, DIMENSION(IRX) :: BETADES, CHDES, CLDES
    REAL :: FOM, PTOT, PVIS, QTOT, QVIS, TDUCT, TGAP, &
            & TGAPZL, TTOT, TVIS, XPAXIS
    REAL, DIMENSION(3, IRX, NRX) :: VABS, VIND, VREL
    !
    ! COMMON /CR_SOLV/
    !
    REAL :: EPSSOLV, RLXSOLV, VAVGINIT
    !
    ! COMMON /CR_SYS/
    !
    REAL, DIMENSION(NSYSX, 0:IPX) :: AICGAM, AICGTH, AICSIG
    REAL, DIMENSION(NSYSX, 0:1) :: AICQFF
    REAL, DIMENSION(NSYSX, 0:NEX) :: AICVWK
    REAL, DIMENSION(NSYSX, 2, 0:IPX) :: AICXYP
    REAL, DIMENSION(0:NSYSX) :: RES
    REAL, DIMENSION(NSYSX, 0:NSYSX) :: SYS
    !
    ! COMMON /CR_TEP/
    !
    REAL, DIMENSION(2, NEX) :: GAMT, GAMT_DX, GAMT_DY, SIGT, &
            & SIGT_DX, SIGT_DY, XPT, YPT
    REAL, DIMENSION(2, 2, NEX) :: GAMT_GAM, GAMT_SIG, GAMT_XP, &
            & GAMT_YP, SIGT_GAM, SIGT_SIG, &
            & SIGT_XP, SIGT_YP, XPT_XP, YPT_YP
    !
    ! COMMON /CR_VELS/
    !
    REAL, DIMENSION(IRX) :: RINFL, VAINFL, VAINFLR, VTINFL, &
            & VTINFLR
    !
    ! COMMON /CR_WAK/
    !
    REAL :: XDWKLEN, XWAKE
    !
    ! COMMON /DF_BBLOC/
    !
    REAL :: BBPFAC, BPLAST
    REAL, DIMENSION(IRX, NRX) :: BBVFAC
    REAL, DIMENSION(IRX) :: CLNEG, CLPOS
    LOGICAL, DIMENSION(NRX) :: LBBLOFT
    LOGICAL :: LBLBL
    !
    ! COMMON /DF_ESLOFT/
    !
    REAL, DIMENSION(NAFX, NRX) :: ALFZ, CAMLO, CAMLOC, PANGTE, &
            & PAREA, PLERAD, TETH, TLOC, &
            & TOCE
    REAL :: APARA, AXHUB, AXTIP, AZTIP, OSHUB, OSTIP, OUTFAC, &
            & PAF, PAXIS, PLOFT, TKHUB, TKTIP
    REAL, DIMENSION(NRX) :: AXHUBQ, AXTIPQ, AZTIPQ, OSHUBQ, &
            & OSTIPQ, PAFQ, PAXISQ, PLOFTQ, &
            & TKHUBQ, TKTIPQ
    REAL, DIMENSION(NLSX) :: AZDFDC, AZLOFT, BECORR, BELOFT, &
            & CDLOFT, TCLOFT, THLOFT, TT1, &
            & TT1S, TT2, TT2S, TT3, YLOFT
    REAL, DIMENSION(NPX, NLSX) :: BLXX, BLYY, TRXX, TRYY
    CHARACTER(80), DIMENSION(NAFX, NRX) :: ENAME
    INTEGER :: ICBS, IHUB, ITIP, ITTYPE, NAF, NLOFT, NLOFT2, &
            & NLOLD, NPP, NPP2
    INTEGER, DIMENSION(NRX) :: ITTYPEQ, NAFQ, NLOFT2Q, NLOFTQ, &
            & NPP2Q
    LOGICAL :: LBLEN, LCALC, LL2D, LLOFT, LROTATE, LSMOD, &
            & LTDEF, LTRAN
    CHARACTER(80) :: LONAME, SNAME
    LOGICAL, DIMENSION(NRX) :: LTDEFQ
    INTEGER, DIMENSION(NAFX) :: NTC
    CHARACTER(80), DIMENSION(NRX) :: SNAMEQ
    REAL, DIMENSION(NAFX, NTCX) :: TCLOC
    REAL, DIMENSION(NLSX, NRX) :: TCLOFTQ, THLOFTQ
    REAL, DIMENSION(NPX, NAFX) :: XXE, YYE
    REAL, DIMENSION(NPX, NAFX, NRX) :: XXEQ, YYEQ
    !
    ! COMMON /DF_MODI/
    !
    REAL :: BLFAC
    REAL, DIMENSION(IRX, NRX) :: BUFBET, BUFCHD, CURBET, CURCHD
    LOGICAL :: LBA, LBC
    REAL, DIMENSION(IRX) :: WB1, WB2, WB3, WC2
    !
    ! COMMON /TEMP_X/
    !
    REAL, DIMENSION(IWX) :: WE1, WE2, WE3
    !
    ! COMMON /XF_PLOTS/
    !
    REAL :: ANGBTEX, APX1BA, APX1BT, APX2BA, APX2BT, AREABX, &
            & CAMBRBX, CHGX, CHORDBX, DXYGX, EI11BA, EI11BT, &
            & EI22BA, EI22BT, GTICKX, RADBLEX, SBLEX, TETHX, &
            & THICKBX, XBMAXX, XBMINX, XCAMBRBX, XGMAXX, XGMINX, &
            & XOFFX, XSFX, XTHICKBX, YBMAXX, YBMINX, YGMAXX, &
            & YGMINX, YOFFX, YSFX
    REAL, DIMENSION(8, NLSX) :: BLENDATA
    INTEGER, DIMENSION(NLSX) :: IXPLOT
    INTEGER :: IXTYPE, NBB, NOVER, NXPLOT
    LOGICAL :: LGEOPLX, LGGRIDX, LGPARMX, LGTICKX
    CHARACTER(80) :: NAMEX
    REAL, DIMENSION(NPX) :: SBB, XBB, XBBP, YBB, YBBP
END MODULE I_DFDC
